### ISSUE TITLE
Add Amadeus character sprite

### ISSUE THREAD

**Issue by Shimizu-kaito** [Loke-60000/Amadeus-chatBot-steins-gate#1]
character sprites might be useful for showing emotion. Compared to other chatbot, character.ai is the most perfect ai reaction and most accurate from the series. Live2d might do too.

**Comment by Loke-60000** [comment]
Yes I thought about it too but I must admit that I'm new in the world of development so with my lack of experience the project will go slowly if it goes at all...
I will probably opt for sprite based animation to get a look closer to the visual novel.

**Comment by Shimizu-kaito** [comment]
Don't give up on ur project, other Amadeus devs has stepped away from their project like 3 to 6 years ago. If you want, try to promote ur project so other devs can help.

**Comment by Loke-60000** [comment]
I'll post something on r/steinsgate but I promise you nothing ahah...

**Comment by Loke-60000** [comment]
https://www.reddit.com/r/steinsgate/comments/11r0um5/operation_heimdall_unleashing_the_power_of_amadeus/

**Comment by Loke-60000** [comment]
new repositories: 
https://github.com/Loke-60000/Amadeus-gpt
